spring:
  datasource:
    username: sa
    password:
    url: jdbc:h2:mem:git

  jpa:
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: create-drop

  h2:
    console:
      enabled: true


server:
  port: 8085